import { useState, useMemo, useRef, useEffect } from "react";
import { Search, FileText, X, CheckCircle2, Eye, Download } from "lucide-react";
import { jsPDF } from "jspdf";
import { serviceReports } from "../../../data/mockTechnician.js";

const STATUS_STYLES = {
  Completed: "bg-emerald-50 text-emerald-700 border-emerald-200",
  Pending:   "bg-amber-50 text-amber-700 border-amber-200",
};

const TYPE_STYLES = {
  Corrective:  "bg-red-50 text-red-600",
  Preventive:  "bg-blue-50 text-blue-700",
  Inspection:  "bg-purple-50 text-purple-700",
};

function Pill({ label, styleMap }) {
  return (
    <span className={`inline-block rounded-full border px-2.5 py-0.5 text-[11px] font-semibold ${styleMap[label] || "bg-neutral-100 text-neutral-500 border-neutral-200"}`}>
      {label}
    </span>
  );
}

// View/Generate Report Modal
function ReportModal({ report, onClose }) {
  if (!report) return null;
  const isCompleted = report.status === "Completed";

  function exportPdf() {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const margin = 18;
    let y = 20;
    const lineH = 7;

    // Header band
    doc.setFillColor(37, 99, 235);          // blue-600
    doc.rect(0, 0, 210, 16, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("DRIVEGUARD AI — Service Report", margin, 11);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Generated: ${new Date().toLocaleString("en-IN")}`, 210 - margin, 11, { align: "right" });

    y = 26;
    doc.setTextColor(17, 24, 39);           // neutral-900

    // Report title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text(`Service Report — ${report.id}`, margin, y);
    y += lineH + 2;

    // Divider
    doc.setDrawColor(229, 231, 235);        // neutral-200
    doc.line(margin, y, 210 - margin, y);
    y += 5;

    // Two-column metadata grid
    const pairs = [
      ["Report ID",    report.id],
      ["Vehicle",      report.vehicleId],
      ["Make / Model", report.vehicleName],
      ["Service Date", report.date],
      ["Service Type", report.type],
      ["Technician",   report.technician],
      ["Work Order",   report.orderId ?? "—"],
      ["Status",       report.status],
    ];

    doc.setFontSize(9);
    pairs.forEach(([k, v], i) => {
      const col = i % 2 === 0 ? margin : 110;
      if (i % 2 === 0 && i > 0) y += lineH;
      doc.setFont("helvetica", "bold");
      doc.setTextColor(107, 114, 128);      // neutral-400
      doc.text(k.toUpperCase(), col, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(17, 24, 39);
      doc.text(String(v), col, y + 4);
    });
    y += lineH + 6;

    doc.line(margin, y, 210 - margin, y);
    y += 6;

    // Findings
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text("FINDINGS", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(17, 24, 39);
    const findLines = doc.splitTextToSize(report.findings, 170);
    doc.text(findLines, margin, y);
    y += findLines.length * 5 + 5;

    // Recommendations
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text("RECOMMENDATIONS", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(17, 24, 39);
    const recLines = doc.splitTextToSize(report.recommendations, 170);
    doc.text(recLines, margin, y);
    y += recLines.length * 5 + 5;

    // Cost breakdown (completed only)
    if (isCompleted && report.totalCost && report.totalCost !== "—") {
      doc.line(margin, y, 210 - margin, y);
      y += 6;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128);
      doc.text("COST BREAKDOWN", margin, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(17, 24, 39);
      [["Labour Cost", report.laborCost], ["Parts Cost", report.partsCost], ["Total Cost", report.totalCost]].forEach(([k, v]) => {
        doc.text(k + ":", margin, y);
        doc.text(String(v), 210 - margin, y, { align: "right" });
        y += lineH;
      });
    }

    // Footer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text("This is a mock service report generated by DriveGuard AI Technician Portal.", margin, 285);

    doc.save(`ServiceReport_${report.id}.pdf`);
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 px-4"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="w-full max-w-xl rounded-2xl border border-neutral-100 bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-neutral-100 px-6 py-4">
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-blue-600" />
            <p className="text-[15px] font-bold text-neutral-900">Service Report — {report.id}</p>
          </div>
          <button onClick={onClose} className="rounded-lg p-1.5 text-neutral-400 hover:bg-neutral-100"><X className="h-4 w-4" /></button>
        </div>
        <div className="space-y-4 p-6">
          <div className="grid grid-cols-2 gap-3 text-[12.5px]">
            {[
              ["Vehicle",    report.vehicleId],
              ["Model",      report.vehicleName],
              ["Report Type",report.type],
              ["Date",       report.date],
              ["Technician", report.technician],
              ["Work Order", report.orderId ?? "—"],
              ["Status",     report.status],
            ].map(([k, v]) => (
              <div key={k}>
                <p className="text-[11px] font-semibold uppercase tracking-wide text-neutral-400">{k}</p>
                <p className="mt-0.5 font-semibold text-neutral-800">{v}</p>
              </div>
            ))}
          </div>

          <div className="rounded-xl border border-neutral-100 bg-neutral-50 p-4 space-y-3">
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-wide text-neutral-400 mb-1">Findings</p>
              <p className="text-[12.5px] text-neutral-700">{report.findings}</p>
            </div>
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-wide text-neutral-400 mb-1">Recommendations</p>
              <p className="text-[12.5px] text-neutral-700">{report.recommendations}</p>
            </div>
          </div>

          {isCompleted && (
            <div className="grid grid-cols-3 gap-3">
              {[["Labour Cost", report.laborCost], ["Parts Cost", report.partsCost], ["Total Cost", report.totalCost]].map(([k, v]) => (
                <div key={k} className="rounded-xl border border-neutral-100 bg-white p-3">
                  <p className="text-[10.5px] font-semibold uppercase tracking-wide text-neutral-400">{k}</p>
                  <p className="mt-0.5 text-[15px] font-extrabold text-neutral-900">{v}</p>
                </div>
              ))}
            </div>
          )}

          <div className="flex justify-end gap-2 border-t border-neutral-100 pt-4">
            <button onClick={onClose}
              className="rounded-lg border border-neutral-200 px-4 py-2 text-[13px] font-medium text-neutral-600 hover:bg-neutral-50">
              Close
            </button>
            {isCompleted && (
              <button
                id={`export-pdf-${report.id}`}
                onClick={exportPdf}
                className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-5 py-2 text-[13px] font-semibold text-white hover:bg-blue-700">
                <Download className="h-4 w-4" /> Export PDF
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ServiceReports() {
  const [reports, setReports]         = useState(() => serviceReports.map((r) => ({ ...r })));
  const [search, setSearch]           = useState("");
  const [typeFilter, setTypeFilter]   = useState("All");
  const [statusFilter, setStatusFilter] = useState("All");
  const [viewReport, setViewReport]   = useState(null);
  const [toast, setToast]             = useState(null);
  const [generatingId, setGeneratingId] = useState(null);
  const toastRef                      = useRef(null);

  useEffect(() => {
    if (!toast) return;
    clearTimeout(toastRef.current);
    toastRef.current = setTimeout(() => setToast(null), 3500);
    return () => clearTimeout(toastRef.current);
  }, [toast]);

  const stats = useMemo(() => ({
    total:     reports.length,
    completed: reports.filter((r) => r.status === "Completed").length,
    pending:   reports.filter((r) => r.status === "Pending").length,
  }), [reports]);

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return reports.filter((r) => {
      const matchSearch = !q || r.id.toLowerCase().includes(q) || r.vehicleId.toLowerCase().includes(q)
        || r.vehicleName.toLowerCase().includes(q) || r.technician.toLowerCase().includes(q);
      const matchType   = typeFilter === "All"   || r.type === typeFilter;
      const matchStatus = statusFilter === "All" || r.status === statusFilter;
      return matchSearch && matchType && matchStatus;
    });
  }, [reports, search, typeFilter, statusFilter]);

  async function handleGenerate(id) {
    setGeneratingId(id);
    await new Promise((r) => setTimeout(r, 1400));
    setReports((prev) => prev.map((r) => r.id === id ? {
      ...r,
      status: "Completed",
      laborCost: "₹1,200",
      partsCost: "₹400",
      totalCost: "₹1,600",
      findings: r.findings.replace("Awaiting completion.", "Service completed successfully."),
      recommendations: "Schedule follow-up check in 30 days.",
    } : r));
    setGeneratingId(null);
    setToast(`Report ${id} generated successfully.`);
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header */}
      <div className="flex items-center gap-2">
        <FileText className="h-5 w-5 text-blue-600" />
        <div>
          <h2 className="text-[18px] font-bold text-neutral-900">Service Reports</h2>
          <p className="text-[13px] text-neutral-400">Review, generate, and export service reports for all vehicles.</p>
        </div>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { label: "Total Reports", value: stats.total,     cls: "text-neutral-900" },
          { label: "Completed",     value: stats.completed, cls: "text-emerald-600" },
          { label: "Pending",       value: stats.pending,   cls: "text-amber-500"   },
        ].map(({ label, value, cls }) => (
          <div key={label} className="rounded-2xl border border-neutral-100 bg-white p-4 shadow-card">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-neutral-400">{label}</p>
            <p className={`mt-1 text-[26px] font-extrabold leading-none ${cls}`}>{value}</p>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-2">
        <div className="relative flex-1 min-w-[200px] max-w-xs">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-neutral-400" />
          <input type="text" placeholder="Search reports…" value={search} onChange={(e) => setSearch(e.target.value)}
            className="w-full rounded-lg border border-neutral-200 bg-white py-2 pl-9 pr-3 text-[13px] placeholder-neutral-400 focus:border-blue-400 focus:outline-none" />
        </div>
        <select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}
          className="rounded-lg border border-neutral-200 bg-white px-3 py-2 text-[13px] text-neutral-700 focus:border-blue-400 focus:outline-none">
          {["All", "Corrective", "Preventive", "Inspection"].map((t) => <option key={t}>{t}</option>)}
        </select>
        <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}
          className="rounded-lg border border-neutral-200 bg-white px-3 py-2 text-[13px] text-neutral-700 focus:border-blue-400 focus:outline-none">
          {["All", "Completed", "Pending"].map((s) => <option key={s}>{s}</option>)}
        </select>
        <span className="ml-auto text-[12px] text-neutral-400">{filtered.length} report{filtered.length !== 1 ? "s" : ""}</span>
      </div>

      {/* Table */}
      <div className="overflow-hidden rounded-2xl border border-neutral-100 bg-white shadow-card">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[820px] border-collapse text-[12.5px]">
            <thead>
              <tr className="border-b border-neutral-100 text-left text-[11px] uppercase tracking-wide text-neutral-400">
                {["Report ID", "Vehicle", "Type", "Date", "Technician", "Work Order", "Total Cost", "Status", "Actions"].map((h) => (
                  <th key={h} className="px-4 py-3 font-semibold">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.length === 0 ? (
                <tr><td colSpan={9} className="py-16 text-center text-[13px] text-neutral-400">No reports match the current filters.</td></tr>
              ) : filtered.map((r) => {
                const isGenerating = generatingId === r.id;
                return (
                  <tr key={r.id} className="border-b border-neutral-50 hover:bg-neutral-50/60 last:border-0 transition">
                    <td className="px-4 py-3 font-bold text-neutral-800">{r.id}</td>
                    <td className="px-4 py-3">
                      <p className="font-semibold text-neutral-800">{r.vehicleId}</p>
                      <p className="text-[11px] text-neutral-400">{r.vehicleName}</p>
                    </td>
                    <td className="px-4 py-3"><Pill label={r.type} styleMap={TYPE_STYLES} /></td>
                    <td className="px-4 py-3 text-neutral-500">{r.date}</td>
                    <td className="px-4 py-3 text-neutral-600">{r.technician}</td>
                    <td className="px-4 py-3 text-neutral-500">{r.orderId ?? "—"}</td>
                    <td className="px-4 py-3 tabular-nums font-semibold text-neutral-700">{r.totalCost}</td>
                    <td className="px-4 py-3"><Pill label={r.status} styleMap={STATUS_STYLES} /></td>
                    <td className="px-4 py-3">
                      <div className="flex flex-col gap-1">
                        <button id={`sr-view-${r.id}`} onClick={() => setViewReport(r)}
                          className="inline-flex items-center gap-1 rounded-md border border-blue-200 px-2.5 py-1 text-[11px] font-semibold text-blue-600 hover:bg-blue-50">
                          <Eye className="h-3 w-3" /> View
                        </button>
                        {r.status === "Pending" && (
                          <button id={`sr-generate-${r.id}`} onClick={() => handleGenerate(r.id)}
                            disabled={isGenerating}
                            className={`rounded-md border px-2.5 py-1 text-[11px] font-semibold transition ${isGenerating ? "cursor-not-allowed border-neutral-200 text-neutral-400" : "border-emerald-200 text-emerald-600 hover:bg-emerald-50"}`}>
                            {isGenerating ? "Generating…" : "Generate"}
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <div className="border-t border-neutral-100 px-4 py-2.5 text-[11.5px] text-neutral-400">
          {filtered.length} of {reports.length} reports shown.
        </div>
      </div>

      {viewReport && <ReportModal report={viewReport} onClose={() => setViewReport(null)} />}

      {toast && (
        <div style={{ position: "fixed", bottom: 24, right: 24, zIndex: 9999 }}
          className="flex max-w-sm items-start gap-3 rounded-xl border border-emerald-200 bg-white px-4 py-3 shadow-lg text-emerald-700">
          <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" />
          <p className="text-[13px] font-medium">{toast}</p>
          <button onClick={() => setToast(null)} className="ml-auto text-neutral-400 hover:text-neutral-600">×</button>
        </div>
      )}
    </div>
  );
}
